quarkus.http.port=8080
quarkus.grpc.server.port=9090
quarkus.grpc.server.host=0.0.0.0
quarkus.http.host=0.0.0.0
quarkus.log.console.json=true
quarkus.micrometer.export.prometheus.enabled=true
jafra.ingest.max-metadata-length=4096
jafra.ingest.max-active-streams=32
jafra.storage.root=/var/lib/jafra/analyzer
%test.jafra.storage.root=target/jafra-analyzer-storage
